-- MySQL Script generated by MySQL Workbench
-- 03/16/17 18:00:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jogoDomino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jogoDomino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jogoDomino` DEFAULT CHARACTER SET utf8 ;
USE `jogoDomino` ;

-- -----------------------------------------------------
-- Table `jogoDomino`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jogoDomino`.`usuario` ;

CREATE TABLE IF NOT EXISTS `jogoDomino`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jogoDomino`.`relatorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jogoDomino`.`relatorios` ;

CREATE TABLE IF NOT EXISTS `jogoDomino`.`relatorios` (
  `idrelatorios` INT NOT NULL AUTO_INCREMENT,
  `tempo_de_jogo` DATETIME NOT NULL,
  `pontuacao` INT(11) NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`idrelatorios`),
  INDEX `fk_realtorios_usuario1_idx` (`fk_usuario` ASC),
  CONSTRAINT `fk_realtorios_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `jogoDomino`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jogoDomino`.`estado_do_jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jogoDomino`.`estado_do_jogo` ;

CREATE TABLE IF NOT EXISTS `jogoDomino`.`estado_do_jogo` (
  `idestado_do_jogo` INT NOT NULL AUTO_INCREMENT,
  `pecas_distribuidas` INT(11) NOT NULL,
  `pecas_nao_distribuidas` INT(11) NOT NULL,
  `pontuacao` INT(11) NOT NULL,
  `tempo_jogado` DATETIME NOT NULL,
  `pecas_jogador` VARCHAR(45) NOT NULL,
  `pecas_computador` VARCHAR(45) NOT NULL,
  `estado_do_jogo` VARCHAR(45) NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`idestado_do_jogo`),
  INDEX `fk_estadoDoJogo_usuario1_idx` (`fk_usuario` ASC),
  CONSTRAINT `fk_estadoDoJogo_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `jogoDomino`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jogoDomino`.`pecas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jogoDomino`.`pecas` ;

CREATE TABLE IF NOT EXISTS `jogoDomino`.`pecas` (
  `idpecas` INT NOT NULL,
  `valor_topo` INT(11) NOT NULL,
  `valor_inferior` INT(11) NOT NULL,
  `peca_associada` INT(11) NOT NULL,
  `fk_estado_do_jogo` INT NOT NULL,
  PRIMARY KEY (`idpecas`),
  INDEX `fk_pecas_estadoDoJogo1_idx` (`fk_estado_do_jogo` ASC),
  CONSTRAINT `fk_pecas_estadoDoJogo1`
    FOREIGN KEY (`fk_estado_do_jogo`)
    REFERENCES `jogoDomino`.`estado_do_jogo` (`idestado_do_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jogoDomino`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jogoDomino`.`login` ;

CREATE TABLE IF NOT EXISTS `jogoDomino`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`idlogin`),
  INDEX `fk_login_usuario_idx` (`fk_usuario` ASC),
  CONSTRAINT `fk_login_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `jogoDomino`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
